services:
  ioturing:
    image: richibrics/ioturing:latest
    # Or from Github:
    # image: ghcr.io/richibrics/ioturing:latest
    container_name: ioturing
    volumes:
      - ~/.config/IoTuring/:/config
    environment:
      - TZ=Europe/Budapest
    restart: unless-stopped